In [2]:
print("hello world")

print("this is it!!")

hello world
this is it!!


In [1]:
l = [1,2,3,4]
for  i in l:
    print(i)

1
2
3
4


In [1]:
import pandas as pd
list1 = [['kriti', 20, 'ktm'],['beth', 30, 'pkr'], ['siya', 10, 'bkt']]
pd.DataFrame(list1 , columns = ['name', 'age', ' address'])

name  age  address
0  kriti   20      ktm
1   beth   30      pkr
2   siya   10      bkt

In [ ]:
list2 = [[10,21,40], [22,24,22], [16,35,13]]
data1 = pd.DataFrame(list2, columns = ['humidity', 'temperature', 'wind'] )
avgg = data1.mean()
avgg

humidity       16.000000
temperature    26.666667
wind           25.000000
dtype: float64

In [ ]:
# numpy
import numpy as np
a = np.array([2,3,4], dtype = np.uint32)             # unsigned integer 32 bit
b = np.array([5,6,7], dtype = np.uint32)
c_unsigned32 = a-b
print('unsigned c : ', c_unsigned32, c_unsigned32.dtype)
c_unsigned32 = a-b.astype(np.int32)
print('signed c : ', c_unsigned32, c_unsigned32.dtype)

unsigned c :  [4294967293 4294967293 4294967293] uint32
signed c :  [-3 -3 -3] int64


In [4]:
np.array([127, 128, 129], dtype = np.int16)

array([127, 128, 129], dtype=int16)

In [6]:
arr = np.arange(10, 20, 2, dtype = np.uint32)
print(arr)
print(arr.dtype)
arr_floats = np.linspace(0,0.24,100, dtype = np.float32)
print(arr_floats)
print(arr_floats.dtype)

[10 12 14 16 18]
uint32
[0.         0.00242424 0.00484848 0.00727273 0.00969697 0.01212121
 0.01454545 0.0169697  0.01939394 0.02181818 0.02424242 0.02666667
 0.02909091 0.03151515 0.0339394  0.03636364 0.03878788 0.04121212
 0.04363636 0.04606061 0.04848485 0.05090909 0.05333333 0.05575757
 0.05818182 0.06060606 0.0630303  0.06545454 0.06787879 0.07030303
 0.07272727 0.07515152 0.07757576 0.08       0.08242425 0.08484849
 0.08727273 0.08969697 0.09212121 0.09454545 0.09696969 0.09939394
 0.10181818 0.10424242 0.10666667 0.10909091 0.11151515 0.1139394
 0.11636364 0.11878788 0.12121212 0.12363636 0.1260606  0.12848485
 0.13090909 0.13333334 0.13575758 0.13818182 0.14060606 0.1430303
 0.14545454 0.14787878 0.15030304 0.15272728 0.15515152 0.15757576
 0.16       0.16242424 0.16484849 0.16727273 0.16969697 0.17212121
 0.17454545 0.17696969 0.17939393 0.18181819 0.18424243 0.18666667
 0.18909091 0.19151515 0.19393939 0.19636364 0.19878788 0.20121212
 0.20363636 0.2060606  0.20848484 0.2109

In [18]:
arr_random = np.random.randint(0,16,(4,4))
arr_random
print(arr_random[0][0])              # access first element of array 0
print(arr_random[0,0])               # alternate of above
print(arr_random[:,:])               # access all element
print(arr_random[0,1])               # access second element of array
print(arr_random[0, :])              # access first row
print(arr_random[:, 1])              # access second column
print(arr_random[1:3 , 1:4])         # access subarray

0
0
[[ 0 11  5  9]
 [ 9  4  0  6]
 [11 13 10  3]
 [ 2 14 15  6]]
11
[ 0 11  5  9]
[11  4 13 14]
[[ 4  0  6]
 [13 10  3]]


In [26]:
np.random.seed(0)
arr = np.random.randint(1, 100, size = (5,5))
print('Original Array:', arr )
print('Boolean indexed arr', arr[arr >50 ])
# print(arr>50)
print(np.where(arr>50 ))

Original Array: [[45 48 65 68 68]
 [10 84 22 37 88]
 [71 89 89 13 59]
 [66 40 88 47 89]
 [82 38 26 78 73]]
Boolean indexed arr [65 68 68 84 88 71 89 89 59 66 88 89 82 78 73]
(array([0, 0, 0, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4, 4, 4]), array([2, 3, 4, 1, 4, 0, 1, 2, 4, 0, 2, 4, 0, 3, 4]))


In [27]:
arr = ['Hello', 'world!'] 
np_array = np.array(arr, dtype = '<U6' )
print('str array: ', np_array)
arr = ['Hello', 'world!'] 
np_array = np.array(arr, dtype = '<U4')
print('str arraynew: ', np_array )


str array:  ['Hello' 'world!']
str arraynew:  ['Hell' 'worl']


In [ ]:
arr_copying = np.array([1,2,3] , [4,5,6 ] )
b = arr_copying
b[2] = 5                            # here b is view of arr_copying (both value change if one change)
print(b)
b = np.copy(a)                      # copy the content of arr_copying to b. view pblm solved